#!/home/cheese/.config/i3/bin/python
import json
from subprocess import PIPE, Popen
# from sys_msg_int import write
from cmd_dict import cmd_dict

# i3 provides json data for workspaces
ws_cmd = Popen(
    ['i3-msg', '-t', 'get_workspaces'],
    stdout=PIPE)
ws_data = ws_cmd.communicate()[0].decode()
ws_dict = json.loads(ws_data)

current_ws = [i['num'] for i in ws_dict if i['visible']][0]

workspace = cmd_dict.get(current_ws, cmd_dict[None])

# write(**workspace['msg'])

Popen(workspace['cmd'])
